- .gitignore
- README.md
- next-env.d.ts
- next.config.js
- package-lock.json
- package.json
- pages/index.mdx
- tsconfig.json
Hello world [NextJS(https://nextjs.org/)] app with 
- static page build
- [MDX](https://mdxjs.com/) to author content in Markdown, but have the flexibility to add components
This is the basic setup with necessary dependencies and updated README file.
How to review
-----
- optional: install `node` if you don't have it already
- go to `http://localhost:3000` to view the page
- Check you see **Hello world**
- optional: Edit `pages/index.mdx` and observe the change
> Create a Hello world app

- Staticfile
- next.config.js
- generate pages as `.index.html`
- serve our custom error page
> Update index page urls for StaticBuild

- components/Button/index.tsx
- pages/get-started/index.mdx
Properties based on https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/components/button/template.njk
> Create a Button component

- layouts/Content/Homepage.tsx
- pages/index.mdx
Homepage has a mixture of 2/3 and full width sections so we need to move that into the page layout
Fun markdown inside inline HTML
> Homepage template and structure

- package-lock.json
- package.json
- pages/_document.js
- styles/application.scss
- add description meta tag
- update govuk-frontend dependency
- import indiviual scss files to reduce bundle size
> App tweaks

- components/SectionNavigation/index.tsx
Use NextJs router method to get the current pathName and compare that with frontMatter __resourcePath
> Add active navigation links to section nav items

- components/SectionNavigation/index.tsx
- next-env.d.ts
- pages/features/application-development.mdx
- pages/features/cloud-security-principles.mdx
- pages/features/constraints.mdx
- pages/features/index.mdx
- pages/features/information-assurance.mdx
- pages/features/observability.mdx
- pages/features/roadmap.mdx
- pages/features/security.mdx
- pages/features/support-and-resolution-times.mdx
- styles/application.scss
Add other pages in the "Features" section
> Add other pages in "Features" section

- pages/_app.js
- pages/_document.js
- public/assets/javascript/govuk-frontend.js
For now we
- vendor in govuk-frontend javascript
- initialise it when `window` is defined in the browser - as pages are SSR-ed
> Initialise gov.uk frontend

- README.md
- package.json
What
---
So we can preview nginx changes without deploying
> Add a npm script to local test nginx configuration

- nginx.conf
- nginx/mime.types
tested with `npm run nginx:local`
> Remove duplicate entries from nginx configs

- redirect/manifest.yml
- redirect/nginx.conf
so cloud.service.gov.uk redirects to www
> redirect: add redirect app

- pages/application-development.mdx
correct the application development page
- replace lets encrypt reference with aws certificate manager
- add influxdb to the list of backing services
> pd-patch-app-dev-page

- pages/pricing.mdx
Does exactly what it says on the tin. 🖌️
> BAU: Fix typo - "that" to "than"

- pages/privacy-notice.mdx
Ticket https://www.pivotaltracker.com/n/projects/1275640/stories/174750509
> Update privacy notice text

- pages/accessibility-statement.mdx
We have shipped https://github.com/alphagov/paas-admin/pull/1051 which replaces the combined datetime input type with individual inputs, in turn addressing the listed issue.
> Amend accessibility statement

- pages/roadmap.mdx
Updated description and links to point to our GitHub roadmap and how to create an issue.
> Updated roadmap links

- pages/accessibility-statement.mdx
- supplier has done some work on the "subscribe to updates" box to add labels
- we have written some custom CSS to improve text contrast
Tickets
- https://www.pivotaltracker.com/n/projects/1275640/stories/174312916
- https://www.pivotaltracker.com/n/projects/1275640/stories/174314019
> Update the accessibility statement

- layouts/Content/Homepage.tsx
- layouts/Content/index.tsx
- lib/rehype-removeTOC.js
- next.config.js
- package-lock.json
- package.json
Fix the failing build by updating a dependency and updating code as per release note requirements as it was a breaking release. This
- removes the top level closure in template files
- updates the next.js config
- update TOC removal logic as the AST data changed because of the closure removal
[Diff without whitespaces](https://github.com/alphagov/paas-product-pages/pull/89/files?diff=split&w=1)
- run `npm install`
- run `npm run local` and check pages look ok
- run `npm run build`, `cd` into the `out` directory and `serve` (if you have it installed), otherwise run a simple httpServer to verify built pages look the same
- evaluate the code
> Update and fix build

- pages/accessibility-statement.mdx
Forgot to update in  https://github.com/alphagov/paas-product-pages/pull/88
> Update a11y statement date

- components/Footer/data.json
- components/Footer/index.tsx
This is to echo the new paas-admin footer.
- run `npm install` (if running for the first time)
- go to `http://localhost:3000` and check the footer for awesomeness
> Update the footer layout and items

- pages/cloud-security-principles.mdx
Update to add more details around response times
> CVE path timings

- nginx.conf
> Temporarily turn CSS cache off

- pages/cookies.mdx
- update 'Session cookies' to 'Essential cookies' heading
- list the consent cookie
- remove stray text (text already in the table)
> Tweak cookies page

- pages/index.mdx
Updated the example services to go with new crests and links
> Updated the example services to go with new crests

- .github/workflows/pr-tests.yml
- components/Button/button.test.tsx
- components/Button/index.tsx
- jest.config.js
- jest.setup.ts
- package-lock.json
- package.json
Setup a testing framework:
- Setup app to use Jest and [Testing Library](https://testing-library.com/) to run tests.
- Remove redundant button component functionality we don't use
- Add button component tests
- Add Github Actions to run test on Pull Request
- clone branch
- run `npm install` to install latest dependencies
-  run `npm test` to verify
- review code
> Setup Jest test runner + button component tests

- nginx.conf
What
---
I spotted on https://securitytxt.org/ we should also have a redirect for `/.well-known/security.txt` So this has been added
How to review
---
Code review
Who can review
---
Anyone
> Added /.well-known/security.txt redirect

- nginx.conf
Pivotal ticket https://www.pivotaltracker.com/n/projects/1275640/stories/178671156
- build the site: `npm run build`
- run in Docker: `npm run nginx:local`
- visit `http://localhost:8080/` and check the headers
> Add Permissions-Policy header

- pages/content/privacy-notice.mdx
Also removed italics on the contact details as they are not to style.
> Updated reference to EEA and ICO email address

- components/Footer/data.json
- components/MastHead/index.tsx
- pages/content/index.mdx
- updated heading, sub-heading and button text
- added 'save time and money section'
- added additional footer links
- several other content tweaks
> Landing page and footer content updates

- pages/content/index.mdx
Includes a link to the youtube video. Separate work will change this to an embedded video for people who accept third party cookies.
> Added new "What is GOV.UK PaaS" section

- pages/content/application-development.mdx
Added OpenSearch, SQS and Autoscaler.
> Added missing backing services

- pages/content/cloud-security-principles.mdx
And no longer part of TechOps.
> Clarifying PaaS to be part of GaaP

- pages/content/accessibility-statement.mdx
Tested status page in https://www.pivotaltracker.com/n/projects/1275640/stories/180210576
BEFORE
**AFTER**
> Update a11y statement

- layouts/HomepageLayout.tsx
Only on the homepage, elsewhere we maintain PageTitle
> Update homepage title attribute

- .github/workflows/pr-tests.yml
Use latest version of checkout and setup-node
Read node version from package.json instead
> Update github actions packages

- components/Footer/data.json
- pages/content/index.mdx
- pages/content/migration-guidance.mdx
Initial version of some migration guidance for tenants migrating to another platform
- clone the branch run locally using the instructions in the README
- check the copy for typos and syntax
- ensure all links work correctly 
- anyone but @pauldougan 
- @wryobservations
> Migration guidance

- pages/content/features.mdx
We have more comprehensive guidance
[Rendered file](https://github.com/alphagov/paas-product-pages/blob/c438cb117a1c85585d5bbbe84a66562baaf429d4/pages/content/features.mdx)
> Remove migration section

- pages/content/migration-guidance.mdx
Add CDN Migration guidance covering the AWS issue with multiple CNAMES in Cloudfront.
> Add CDN Migration guidance

- pages/content/migration-guidance.mdx
Newest version of DM works differently so best to just link to the service and let people work it out.
Fixes https://github.com/alphagov/paas-product-pages/issues/332
> Replace link to DM g-cloud search results

- pages/content/accessibility-statement.mdx
Some issue in StatusPage have been addressed. See https://github.com/alphagov/notifications-admin/pull/4803 for more details
> Update accessibility statement

- .github/dependabot.yml
- .github/workflows/pr-tests.yml
Description:
- Pin GitHub actions to hashes
- Configure dependabot to create PRs against GitHub actions
> BAU - Configure dependabot for GitHub actions

- .github/workflows/deploy.yml
Description:
- deploy.yml is failing because it is attempting to login but the cf-cli isn't installed
> 185827634 - Fix deploy by adding cf cli

- .github/workflows/deploy.yml
Description:
- Switches to the proper directory as we are already in `paas-product-pages` directory
> 185827634 - Switch to correct directory to fix pipeline

- pages/content/migration-guidance.mdx
What
----
Updating the docs to include additional migration advice
How to review
-------------
Follow the readme instruction to render the docs locally
Review the changed section(s)
Who can review
--------------
Any team member
> updating migration advice/details

- components/Header/index.tsx
- config/config.json
- pages/_app.tsx
- pages/content/index.mdx
- styles/application.scss
- Add 'decommissioned' messaging to homepage
- Remove bits that are not needed
> [186578173] check-post-decomission

- pages/content/features.mdx
- pages/content/support-and-response-times.mdx
- Tenant page documentation update.
> Tenant page documentation update
