.gitignore
package-lock.json
pages/_document.js

For our pages to have a GOV.UK look to them, we need to use the template from [GOV.UK Design System](https://design-system.service.gov.uk/styles/page-template/)
To do this in NextJS apps we need to declare a custom `Document`
as described in [NextJS docs](https://nextjs.org/docs/advanced-features/custom-document)
This will add the necessary HTML markup to our pages, but they still won't be styled.
**Before**
**After**
- go to http://localhost:3000 to view the page
- Check you see the update HTML markup from `pages/_document.js`

Create a document HTML template

---

components/Footer/data.json
components/Footer/index.tsx
pages/_document.js
styles/application.scss

Create a site-wide footer component based on the [GOV.UK Design System component](https://design-system.service.gov.uk/components/footer/) but only with the "meta" section for now
The component utilises a JSON data file for it's links data.
PR also contains minor HTML markup fixes and updated stylesheet to avoid leaking element styles into components.
**Note: this component is lacking tests. [Here's an upcoming story to set up a testing framework](https://www.pivotaltracker.com/n/projects/1275640/stories/173075868)**
- go to http://localhost:3000 to check the footer is looking as per …

Create a Footer component

---

components/Header/data.json
components/Header/index.tsx
next-env.d.ts
pages/_document.js
styles/application.scss

Create a site-wide header component based on the [GOV.UK Design System
component](https://design-system.service.gov.uk/components/header/)
The component utilises a JSON data file for product name and navigation
links.
We'll set up, bundle and initialise govuk-frontend javascript in a separate ticket
**Note: this component is lacking tests. There's an upcoming story to set
up a testing framework.**
This PR also contains 
- style tweaks for the header to allow for the long PaaS name 
- an extension of the `SVGImage` element to allow for src attribute on the `<image>` child element which GOV.UK Frontend uses to provide a fallback crown logo for IE8.
- checkout the `header-component` branch
- install dependencies with `npm …

Create a Header component

---

pages/404.js

Replace the NextJS default 404 page with a pattern from
[GOV.UK Design system](https://design-system.service.gov.uk/patterns/page-not-found-pages/) as per [NextJS docs](https://nextjs.org/docs/advanced-features/custom-error-page)
Content was adapted from the existing 404 page: https://www.cloud.service.gov.uk/bb
Note: When #5 get's merged in, header will look better :)
- checkout the `404-page` branch
- go to `http://localhost:3000/whatever` to check the page is looking as per https://design-system.service.gov.uk/patterns/page-not-found-pages/
- review the code for any improvements

Create a custom 404 page

---

layouts/PagewithSideNav.tsx
pages/_document.js
pages/get-started/index.mdx
tsconfig.json

For pages in sections, we need a layout that has room for section side navigation.
This layout will be parsed by MDX if specified as a layout for each page and render the proper HTML markup
Example of existing page layout: https://www.cloud.service.gov.uk/get-started
- checkout the `page-with-sidenav-layout` branch
- go to `http://localhost:3000//get-started` to check the page content is in a 2/3 grid layout
- review the code for any improvements

Create a Page-with-sidenav layout

---

pages/404.js

Wrap in generic layout and replace `class` with `className` to remove errors

Fix 404 page

---

next.config.js
package-lock.json
package.json
styles/application.scss

MDX already uses remark and rehype to turn markdown into HTML,
so this to plugins naturally fit in and apply IDs and anchor links to headings.

Heading anchor links

---

components/Footer/data.json

We currently don't store any cookies

Remove cookies page link in the footer

---

nginx.conf

Updated a few settings to maximise caching:
- JS was being served as `application/x-javascript`, so this has been added (alternative: serve everything as application/javascript)
- images upped to max time to follow expectations set by [Lighthouse](https://web.dev/uses-long-cache-ttl/#how-to-cache-static-resources-using-http-caching)
- add `immutable` to the static files following guidance on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#Caching_static_assets)

Update the config to maximise caching

---

nginx.conf
nginx/mime.types

Very small tweak to the setup. 
- Removed duplicate woff/woff2 reference in mime.types, so now using `font/woff`, `font/woff2`
- JS now being served as `application/javascript` as mentioned in [RFC 4329](http://www.rfc-editor.org/rfc/rfc4329.txt)

Small tweak to the mimetypes being sent and the caching applied

---

nginx.conf
pages/sign-in.mdx
styles/application.scss

Add a sign-in page where users select which region they'd like to sign into PaaS admin in.
Form uses HTML from the Design system directly.
Massive help by @tlwr on this, writing the nginx solution
[Story](https://www.pivotaltracker.com/n/projects/1275640/stories/173330663)

Add a sign in page

---

layouts/Content/index.tsx
styles/_section-navigation.scss

Users use the skip link to skip to content, at the moment they have to tab through the
section navigation to get to the main content.
This moves the navigation outside the main element and adjusts the spacing

Move section nav out of main element

---

package-lock.json
package.json

- [Changelog for govuk-frontend v3.8.0](https://github.com/alphagov/govuk-frontend/releases/tag/v3.8.0)
- npm audit log
```
found 451 low severity vulnerabilities in 1329 scanned packages
run `npm audit fix` to fix 451 of them.
paas-product-pages % npm audit fix
npm WARN paas-product-pages@1.0.0 No repository field.
updated 1 package in 6.733s
100 packages are looking for funding
run `npm fund` for details
fixed 451 of 451 vulnerabilities in 1329 scanned packages
paas-product-pages % npm audit
=== npm audit security report===
found 0 vulnerabilities
in 1329 scanned packages
```

Bump govuk-frontend and audit npm dependencies

---

nginx.conf

Add  redirect for `cloud.service.gov.uk/support` to redirects to `https://admin.london.cloud.service.gov.uk/support`
Requested by Mr. Duggan: "as a tech arch I spend a lot of time pointing people to things either via slack, hangouts, docs, sheets, slides and having easily memorable permalinks helps when in meetings"
- install docker
- run `npm install`
- run `npm run build`
- run `npm run nginx:local`
- visit `http://localhost:8080/support` to be redirected to  `https://admin.london.cloud.service.gov.uk/support`

Add redirect for /support

---

pages/sign-in.mdx

DAC audit raised an issue that there was no error when users hit
continue without selecting an option.
As these are static pages, we don/t have a way to check if an option
was selected to throw an error.
That's why we're pre-selecting the first option.

Pre-select sign-in region radio option

---

nginx.conf
pages/cloud-security-principles.mdx
pages/features.mdx
pages/pricing.mdx

- correctly link to the /support-and-response-times page
- fix url redirect, so that ` /support-and-response-times` doesn't get redirect necessarily

Fix broken things

---

components/Footer/data.json
pages/cookies.mdx

We use this page to state which strictly necessary cookies we store on cloud.service subdomains as it's open to all for any IA information gathering needs
[Rendered version](https://github.com/alphagov/paas-product-pages/blob/c7a0237453ae3d960086b21e811b8b67ed8e79a2/pages/cookies.mdx)

Reinstate cookies page

---

package-lock.json
package.json

Next 9.5.2 introduced a breaking change https://github.com/vercel/next.js/pull/14325 which hasn't been address in the downstream package yet https://github.com/hashicorp/next-mdx-enhanced/issues/74
Until such time, we'll pin next to 9.5.1

Fix failing build

---

components/MastHead/index.tsx
layouts/Content/Homepage.tsx

Adjust title and main heading to create association for screenreader
users. This is a usability issue, not a WCAG issue
“The page title was reported by JAWS as ‘GOV.UK Platform as a Service’.
However, the level 1 heading on the homepage is ‘Host your service in
the cloud’. This is confusing because it is unclear as to what the page
refers. When combined, page titles and level 1 headings describe the
purpose and function of a page and its content. I would therefore expect
he page title and level 1 heading to match.”
Ticket: https://www.pivotaltracker.com/n/projects/1275640/stories/174314818

Associate homepage page title and heading

---

components/MastHead/index.tsx
layouts/Content/Homepage.tsx
styles/_masthead.scss
styles/application.scss

Having breadcrumbs inside main element cause the skipLink to fail to focus correctly.
Issue is very evident in IE11, where focus goes back to the skipLink
Fixes: https://www.pivotaltracker.com/n/projects/1275640/stories/174315267
No visual changes.
- go to localhost:3000 and compare homepage against live
- use Tab key to get to Skip Link. Press ENTER, then Tab again.
- Focus should now be on the "How to get started" button

Move homepage breadcrumb out of main element

---

components/MastHead/index.tsx
pages/constraints.mdx
pages/get-started.mdx
pages/index.mdx
pages/migrate-a-live-service.mdx

This to fix Non-Descriptive Links out of Context WCAG issue when links are viewed out of context, giving link only text more context
Related ticket: https://www.pivotaltracker.com/n/projects/1275640/stories/174314514

Fix links Non-Descriptive Links out of Context WCAG 2.1 issue 

---

lib/rehype-removeTOC.js
next.config.js
package-lock.json
package.json
styles/application.scss

Problem:
DAC audit found that 
> An underlined hash is displayed with mouse hover of the level-two headings on the ‘GOV.UK Platform as a Service’ page. The purpose of the hash is unclear as this only appears to direct users’ focus to the adjacent heading when selected. Also, they are not accessible to standard keyboard commands.
We implemented that feature to allow us to provide deep-links in engagement.
Solution:
Instead on providing this functionality on mouse hover only, we now generate a page table of contents based on headings' IDs, that are anchor links to them. This way we retain the functionality and also make it accessible to everyone.
To generate table of content's we're using [rehype-toc](https://github.com/JS-DevTools/rehype-toc) plugin. 
This generates a TOC on every page, …

Generate page contents list

---

components/Header/index.tsx

Problem:
The aria-label for the 'Menu' button in the header does not include
'menu' despite the button being labelled with the text 'menu'.
This fails WCAG 2.5.3 - Label in name, as flagged in an audit of Digital Marketplace.
Solution:
Add the word 'menu' to the button aria-label

Update main navigation menu label

---

next.config.js

This will make is distinguishable from the main navigation for screenreader users

Add label to table of contents navigation element

---

styles/application.scss

Previous spacing was too tight, especially on mobile

Increase space between table of content links

---

components/Footer/data.json
components/Footer/index.tsx
pages/accessibility-statement.mdx

Add accessibility statement for PaaS products. Content reviewed by the tech writer. 
[Pivotal ticket](https://www.pivotaltracker.com/n/projects/1275640/stories/174362862)
Move "Built by GDS" to a new line  as per GOV.UK Design system
[Rendered version](https://github.com/alphagov/paas-product-pages/blob/a11y-statement/pages/accessibility-statement.mdx)
- run `npm install`
- view the page in browser
Visual changes
--------------

Add the accessibility statement

---

components/Footer/data.json
components/Footer/index.tsx

To customise the footer items and sections, we use a JSON config file.
We import that file into the component view and populate.
Not all properties are required, but when omitted, Typescript will throw an error.
To mitigate, we now list all properties in the JSON file, but specify a
`null` or empty values.
Additionally checks if the view have been updated so that they don't output any empty markup.
- run `npm run build` to test the build has no errors
- `cd` into `out` directory
- run `npx serve` to serve the static files
- view the page: footer should have the new layout, and there shouldn't be a `govuk-footer__inline-list` element inside `govuk-footer__meta`

Fix failing build for optional props

---

components/Footer/data.json

Link to our channel on cross-gov Slack instance to be consistent with Pay and Notify.
- click on the footer link. if signed into slack it should open the govuk-paas channel

Link to our channel on cross-gov Slack instance

---

pages/cookies.mdx

Fix missing padding and bottom border on the 'Expires' cell for 'JSESSIONID' within the session cookies table, by adding the same `govuk-table__cell` class used on the other cells.

Add missing class name to table cell

---

components/CookieBanner/index.tsx
javascripts/cookie-functions.js
styles/cookie-banner.scss

Add yes/no to quickly accept or deny cookies and initialise GA
Follows Pay and Notify interaction
- check out branch
- run`npm install`
- set `this.cookieDomain` to empty string for localhost test in cookie-functions.js
- visit http://localhost:3000
- if you haven't set a preference you will see a banner
- save a cookie preference
- check if have cookies stored (chrome: Option + ⌘ + J (on macOS), or Shift + CTRL + J (on Windows/Linux) - Application tab

Update cookie banner interaction

---

javascripts/cookie-functions.js
pages/cookies.mdx

- Update our cookie implementation to use [gtag.js](https://developers.google.com/analytics/devguides/collection/gtagjs), same as what we're going to use on paas-admin.
- Tweak to the way we get referal link
- Update cookies table with the new cookie
check out branch
- run `npm install`
- set `this.cookieDomain` to empty string for localhost test in cookie-functions.js
- visit http://localhost:3000
- if you haven't set a preference you will see a banner
- save a cookie preference
- check if have cookies stored (chrome: Option + ⌘ + J (on macOS), or Shift + CTRL + J (on Windows/Linux) - Application tab

Update cookie functions

---

pages/security.mdx

To keep our security details in line with the MoU we are stating 'appropriate security clearance'

Change to 'appropriate security clearance'

---

nginx.conf
pages/_document.js

Implement more security by
- reducing server info
- adding security headers
- implementing a Content Security policy
using nginx configuration. See each commit for detailed explanation.
Remedial work from the ITHC report, pages 41-46. Also good practice.
- review by commit
- check https://paas-product-pages.london.cloudapps.digital/ where this has been deployed to
- accept cookies to check JS is working, check images and fonts are served
curl -I https://www.cloud.service.gov.uk
content-type: text/html; charset=utf-8
content-length: 16712
accept-ranges: bytes
cache-control: no-cache
cache-control: public, immutable
**server: nginx/1.17.10**
strict-transport-security: max-age=31536000; includeSubDomains; preload
vary: Accept-Encoding
curl -I …

Implement security headers and Content Security Policy

---

javascripts/cookie-functions.js

What
----
No arrow functions allowed in client-side JS
How to review
-------------
- set `this.cookieDomain` to empty string for localhost test in cookie-functions.js
- start the app
- save a cookie preference
- check if have cookies stored (chrome: Option + ⌘ + J (on macOS), or Shift + CTRL + J (on Windows/Linux) - Application tab
Who can review
---------------
not @kr8n3r

Replace ES6 syntax with ES5 in cookie-functions

---

components/CookieBanner/index.tsx

change "Paas" to "GOV.UK PaaS"

Update cookie banner text

---

.dir-locals.el
javascripts/analytics.js
javascripts/analytics.test.js
javascripts/application.js
javascripts/cookie-functions.js
jest.config.js
lib/rehype-removeTOC.js
next.config.js
package-lock.json
package.json
pages/_app.js
pages/_document.js
rollup.config.js
test.sh

In order to run standard, I've modified `npm test`, so it now that runs standard followed by jest.
Two new npm targets are added by this PR:
1. `npm run lint`
2. `npm run lint-fix`

add custom test hook

---

components/CookieBanner/index.tsx
components/Footer/data.json
components/Footer/index.tsx
components/Header/index.tsx
javascripts/application.js
package-lock.json
package.json
pages/_document.tsx

- update govuk-frontend to v4.0.0
- make changes as per https://github.com/alphagov/govuk-frontend/releases/tag/v4.0.0 where needed
- check commits for code changes
- clone branch
- install updated dependencies (`npm install`)
- build the site (`npm run build`)
- `cd` into `out` folder and serve the page (`npx serve`)
- check page on `localhost:5000` for any issues
There are [expected warnings in CSS compilation](https://github.com/alphagov/govuk-frontend/issues/2238) coming from govuk-frontend
`npm install` will output 6 high severity vulnerabilities. Currently no fix available for that.

Update to govuk-frontend v4.0.0 with required changes

---

.github/workflows/pr-tests.yml
package.json

Build and run tests on node 16, which is now the active LTS version.
As for the production build, it [looks like it's already happening on active LTS](https://github.com/alphagov/paas-release-ci/blob/1e92b932e4cca0dbed7f51132b37cc79a704e070/pipelines/plain_pipelines/paas-product-pages.yml#L34-L41)
[Node docker image with `LTS` tag](https://hub.docker.com/layers/node/library/node/lts/images/sha256-3ab154b75ddea8612aa4669a144f4b8f5ab80e0e1f47a6f835ad93dfe5cb851c?context=explore)
- clone branch
- update your version of node to latest LTS (install from [node.js](https://nodejs.org/en/download/) or use nvm)
- install updated dependencies (`npm install`)
- build the site (`npm run build`)
- `cd` into `out` folder and serve the page (`npx serve`)
- check page on `localhost:5000` for any issues …

Build and run tests on node v16

---

pages/content/sign-in.mdx

Fix sign-in page form styles
markdown parser has new rules that adds `<p>` tag if empty space

Fix sign-in page form styles

---

nginx.conf
pages/_document.tsx

In https://github.com/alphagov/paas-product-pages/pull/117 we implemented Content security policy (CSP) with a generated nonce value as using a hash didn't work.
Now using a hash works, so we can remove the generated nonce value and use the govuk-frontend provided SHA - https://frontend.design-system.service.gov.uk/importing-css-assets-and-javascript/#use-a-hash-to-unblock-inline-javascript
- requirement Docker Desktop
- clone and build `npm run build`
- start Docker Desktop
- run `npm run nginx:local`
- visit `http://localhost:8080`
- check no error in dev tools console and javascript still works - shrink to mobile view and check header menu toggle)

Use hash for CSP

---

nginx.conf

Redirect /roadmap to /
We have decommissioned the roadmap and we don;t want to serve a 404 page
- requirement Docker Desktop
- clone and build `npm run build`
- start Docker Desktop
- run `npm run nginx:local`
- visit `http://localhost:8080/roadmap`

Redirect /roadmap to /

---

pages/content/pricing.mdx

Remove "How to start using the paid service" section from the /pricing page
It talks about trial accounts and option to upgrade

Remove section on trial accounts and upgrades

---

components/Footer/data.json

It's going away in https://www.pivotaltracker.com/story/show/183022217

Remove link to performance dashboard

---

pages/content/migration-guidance.mdx

We made a couple of mistakes, but we've also realised using quarters can be confusing as it's unclear whether we are talking about the calendar or financial year.
Hopefully fixes #288

Fix some dates and clarify others

---

.github/workflows/pr-tests.yml
package-lock.json
package.json

V18 is now LTS so it makes sense to upgrade.
[requires a move to ubuntu 20 build on GHA](https://github.com/alphagov/paas-product-pages/actions/runs/3829737255/jobs/6516761409#step:4:8)

Update to node v18

---

manifest.yml

update to use latest non-pinned nginx buildpack
resolves  https://concourse.build.ci.cloudpipeline.digital/builds/62003569

Use latest builpack in cf manifest

---

nginx.conf
pages/content/sign-in.mdx

Instead of a form using nginx redirect, just use links to the relevant region sign in.
Will make it easier to deploy elsewhere, outside paas
**Before**
**After**

Simplify signin mechanism

---

.babelrc
components/Button/button.test.tsx
jest.config.js
jest.setup.ts
next.config.js
next.config.mjs
package-lock.json
package.json
vite.config.ts
vitest.setup.ts

Replace Jest with [Vitest](https://vitest.dev/) including new config files, settings, test update and dependency updates
Vite is quicker, works with ES modules and I'm using this as testing ground to do the work on the much more complex paas-admin migration
- the test pass
- [run locally](https://github.com/alphagov/paas-product-pages?tab=readme-ov-file#local-development)
- check the [static build](https://github.com/alphagov/paas-product-pages?tab=readme-ov-file#review-static-build-production-build)
Jest: [Time: 1.3 s](https://github.com/alphagov/paas-product-pages/actions/runs/8043216385/job/21964949932#step:5:25)
Vitest: [Duration 759ms](https://github.com/alphagov/paas-product-pages/actions/runs/8046101761/job/21972673446#step:5:23)

Migrate from Jest to Vitest
